remote_theme:       Startbootstrap/startbootstrap-clean-blog-jekyll

title:              OSS-Quiz(2)
email:              haimnam10@gmail.com
description:        남하임의 개인 정적 페이지
author:             2017310608 남하임
baseurl:
url:                "https://haimnam.github.io"

# Social Profiles
twitter_username:   
github_username:    haimnam
facebook_username:  haimnam
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
